<?php

function vsite_score_radioactivity_info() {
  $q = db_query('SELECT type, name FROM {node_type}');
  $types = array();
  while ($node_type = db_fetch_object($q)) {
    $types[$node_type->type.'_create'] = array(
      'title_placeholder' => 'Create '.$node_type->name,
      'description' => 'Energy added to this vsite when a '.$node_type->name.' is created.',
    );
  }

  return array (
    'targets' => array(
      'vsite' => array(),
    ),
    'sources' => array(
      'vsite' => $types,
    ),
  );
}

/**
 * Implementation of hook_views_api().
 */
function vsite_score_views_api() {
  return array(
    'api' => 2,
  );
}

/**
 * Impelementation of hook_nodeapi().
 * Update the vsite's energy to include a new node's.
 */
function vsite_score_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'insert':

      if (is_array($node->og_groups)) {
        foreach ($node->og_groups as $og) {
          radioactivity_add_energy($og, 'vsite', $node->type.'_create');
        }
      }

      /*
      $q = db_query('SELECT SUM(energy) AS total_energy FROM {radioactivity}
  														INNER JOIN {node} ON id = nid
  														INNER JOIN {og_ancestry} USING (nid)
  														WHERE group_nid = %d GROUP BY decay_profile', key($node->og_groups));

      while ($r = db_fetch_array($q)) {
        $energy = array(
          'id' => key($node->og_groups),
          'class' => 'node',
          'decay_profile' => $r['decay_profile'],
          'energy' => $r['total_energy'],
        );
        $energy = (object) $energy;
        drupal_write_record('radioactivity', $energy, 'id');
      } */

      // the other option is digging through decay profiles manually,
      // looking for the exact energy for adding a node type and adding that
      // to the vsite's energy.

      // or, adding a new type that sets the radioactivity for creation events straight to vsite

    break;
  }
}