<?php

function vsite_score_radioactivity_info() {
  $q = db_query('SELECT type, name FROM {node_type}');
  $types = array();
  while ($node_type = db_fetch_object($q)) {
    $types[$node_type->type.'_create'] = array(
      'title_placeholder' => 'Create '.$node_type->name,
      'description' => 'Energy added to this vsite when a '.$node_type->name.' is created.',
    );
  }

  return array (
    'targets' => array(
      'vsite' => array(),
    ),
    'sources' => array(
      'vsite' => $types,
    ),
  );
}

/**
 * Impelementation of hook_nodeapi().
 * Update the vsite's energy to include a new node's.
 */
function vsite_score_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'insert':

      if (is_array($node->og_groups)) {
        foreach ($node->og_groups as $og) {
          radioactivity_add_energy($og, 'vsite', $node->type.'_create');
        }
      }
    break;
  }
}

/**
 * Implementation of hook_views_api().
 */
function vsite_score_views_api() {
  return array(
    'api' => 2,
  );
}