<?php

function vsite_score_menu() {
  $menu = array();
  $menu['score'] = array(
    'title' => 'Vsite Score',
    'page callback' => 'vsite_score_page',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );
  return $menu;
}

function vsite_score_page() {
  $vsite = vsite_get_vsite();

  $q = db_query("SELECT nid, (SELECT SUM(energy) FROM {radioactivity}
  														INNER JOIN {node} ON id = nid
  														INNER JOIN {og_ancestry} USING (nid)
  														WHERE group_nid = n.nid) AS score
  							FROM {node} AS n WHERE type = 'vsite' ORDER BY score DESC LIMIT 5");

  $s = '<pre>';
  while ($r = db_fetch_array($q)) {
    $s .= print_r($r,1);
  }
  $s .= print_r(radioactivity_get_decay_profiles(),1);
  $s .= print_r($vsite,1);
  $s .= '</pre>';
  return $s;
}

/**
 * Implementation of hook_views_api().
 */
function vsite_score_views_api() {
  return array(
    'api' => 2,
  );
}

/**
 * Impelementation of hook_nodeapi().
 * Update the vsite's energy to include a new node's.
 */
function vsite_score_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'view':
      // group = key($node->og->groups);
  }
}